SemedInstitucional/Controllers/EscolasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SemedInstitucional.Models.Utilidades;
using Microsoft.AspNet.Identity.Owin;

using SemedInstitucional.Models;

namespace SemedInstitucional.Controllers
{
    public class EscolasController : Controller
    {
        private ApplicationDbContext _db;

        public EscolasController()
        {
        }

        public EscolasController(ApplicationDbContext db)
        {
            _db = db;
        }

        public ApplicationDbContext db {
            get {
                return _db ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set {
                _db = value;
            }
        }

        public async Task<ActionResult> RedesEnsino()
        {
            try
            {
                List<IGrouping<Nucleo,Escola>> escolas = await db.Escolas
                    .Where(x => x.Deletado == false).GroupBy(y => y.Nucleo).ToListAsync();
                return View(escolas);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_ACTION + release.Message;
                return RedirectToAction("Login", "Account");
            }
        }

        // GET: Escolas
        public async Task<ActionResult> Index()
        {
            try
            {

                var escolas = db.Escolas.Where(x => x.Deletado == false).Include(e => e.Nucleo);
                return View(await escolas.ToListAsync());

            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_ACTION + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Escolas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Escola escola = await db.Escolas.Where(x => x.ID == id).Include(e => e.Nucleo).FirstOrDefaultAsync();
                if (escola == null)
                {
                    return HttpNotFound();
                }
                return View(escola);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_DETAILS + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Escolas/Create
        public ActionResult Create()
        {
            ViewBag.NucleoID = new SelectList(db.Nucleos.Where(x => x.Deletado == false), "ID", "Nome");
            return View();
        }

        // POST: Escolas/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Escola escola)
        {
            try
            {
                escola.CreateRegister("Teste");
                db.Escolas.Add(escola);
                await db.SaveChangesAsync();
                TempData["Mensagem"] = SystemMessage.SUCCESS_CREATE;
                return RedirectToAction("Index");
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_CREATE + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Escolas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Escola escola = await db.Escolas.FindAsync(id);
                if (escola == null)
                {
                    return HttpNotFound();
                }
                ViewBag.NucleoID = new SelectList(db.Nucleos.Where(x => x.Deletado == false), "ID", "Nome", escola.NucleoID);
                return View(escola);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_EDIT + release.Message;
                return RedirectToAction("Index");
            }
        }

        // POST: Escolas/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Escola escola)
        {
            try
            {
                Escola obj = db.Escolas.Find(escola.ID);
                obj.Nome = escola.Nome;
                obj.NucleoID = escola.NucleoID;
                db.Entry(obj).State = EntityState.Modified;
                await db.SaveChangesAsync();
                TempData["Mensagem"] = SystemMessage.SUCCESS_EDIT;
                return RedirectToAction("Index");
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_EDIT + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Escolas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Escola escola = await db.Escolas.Where(x => x.ID == id).Include(e => e.Nucleo).FirstOrDefaultAsync();
                if (escola == null)
                {
                    return HttpNotFound();
                }
                return View(escola);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_DELETE + release.Message;
                return RedirectToAction("Index");
            }
        }

        // POST: Escolas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                Escola escola = await db.Escolas.FindAsync(id);
                escola.DeleteRegister("");
                db.Entry(escola).State = EntityState.Modified;
                await db.SaveChangesAsync();
                TempData["Mensagem"] = SystemMessage.SUCCESS_DELETE;
                return RedirectToAction("Index");
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_DELETE + release.Message;
                return RedirectToAction("Index");
            }
        }

        public async Task<JsonResult> GetList(string search)
        {
            var obj = await db.Escolas
                    .Where(x => x.ID.ToString().Contains(search) && x.Deletado == false)
                    .Select(x => new { id = x.ID, text = x.ID })
                    .ToListAsync();
            return Json(new { items = obj }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SemedInstitucional/Controllers/GruposController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SemedInstitucional.Models.Utilidades;
using Microsoft.AspNet.Identity.Owin;

using SemedInstitucional.Models;

namespace SemedInstitucional.Controllers
{
    public class GruposController : Controller
    {
        private ApplicationDbContext _db;

        public GruposController()
        {
        }

        public GruposController(ApplicationDbContext db)
        {
            _db = db;
        }

        public ApplicationDbContext db {
            get {
                return _db ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set {
                _db = value;
            }
        }

        // GET: Grupos
        public async Task<ActionResult> Index()
        {
            try
            {
                return View(await db.Grupos.Where(x => x.Deletado == false).ToListAsync());
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_ACTION + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Grupos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Grupo grupo = await db.Grupos.Where(x => x.ID == id).FirstOrDefaultAsync();
                if (grupo == null)
                {
                    return HttpNotFound();
                }
                return View(grupo);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_DETAILS + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Grupos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Grupos/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Grupo grupo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    grupo.CreateRegister("Teste");
                    db.Grupos.Add(grupo);
                    await db.SaveChangesAsync();
                    TempData["Mensagem"] = SystemMessage.SUCCESS_CREATE;
                    return RedirectToAction("Index");
                }

                return View(grupo);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_CREATE + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Grupos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Grupo grupo = await db.Grupos.FindAsync(id);
                if (grupo == null)
                {
                    return HttpNotFound();
                }
                return View(grupo);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_EDIT + release.Message;
                return RedirectToAction("Index");
            }
        }

        // POST: Grupos/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Grupo grupo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Grupo obj = db.Grupos.Find(grupo.ID);
                    obj = grupo;
                    db.Entry(obj).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    TempData["Mensagem"] = SystemMessage.SUCCESS_EDIT;
                    return RedirectToAction("Index");
                }
                return View(grupo);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_EDIT + release.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Grupos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Grupo grupo = await db.Grupos.Where(x => x.ID == id).FirstOrDefaultAsync();
                if (grupo == null)
                {
                    return HttpNotFound();
                }
                return View(grupo);
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_DELETE + release.Message;
                return RedirectToAction("Index");
            }
        }

        // POST: Grupos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                Grupo grupo = await db.Grupos.FindAsync(id);
                grupo.DeleteRegister("");
                db.Entry(grupo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                TempData["Mensagem"] = SystemMessage.SUCCESS_DELETE;
                return RedirectToAction("Index");
            }
            catch (Exception release)
            {
                TempData["Mensagem"] = SystemMessage.ERROR_DELETE + release.Message;
                return RedirectToAction("Index");
            }
        }

        public async Task<JsonResult> GetList(string search)
        {
            var obj = await db.Grupos
                    .Where(x => x.ID.ToString().Contains(search) && x.Deletado == false)
                    .Select(x => new { id = x.ID, text = x.ID })
                    .ToListAsync();
            return Json(new { items = obj }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SemedInstitucional/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SEMED INSTITUCIONAL</title>
    <!-- Custom fonts for this template-->
    <link href="~/SbAdmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/SbAdmin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top" class="sidebar-toggled" style="background-color:white;">
    <div id="wrapper">
        <div id="content-wrapper" class="d-flex flex-column" style="background-color: white;">
            <div id="content">
                @Html.Partial("_LoginPartial")
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <footer class="sticky-footer bg-white fixed-bottom" style="background-color:#c7c7c7;
        background: linear-gradient(to bottom,rgba(255,255,255,1) 0%,rgba(255,255,255,1) 10%,rgb(230, 230, 230) 100%);
        padding:25px 25px; height: 120px;">
                <div class="col-md-6 offset-md-3">
                    <hr />
                </div>
                
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <p style="font-size:14px; margin-bottom: 5px; font-weight: bold;">SEMED - Sede</p>
                        <p style="font-size:11px; margin-bottom: 5px;">Av. Marechal Castelo Branco, Q. 14, n° 250 - Ed. Trade Center</p>
                        <p style="font-size:11px;">Bairro São Francisco</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="~/SbAdmin/vendor/jquery/jquery.min.js"></script>
    <script src="~/SbAdmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/SbAdmin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/SbAdmin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/SbAdmin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/SbAdmin/js/demo/chart-area-demo.js"></script>
    <script src="~/SbAdmin/js/demo/chart-pie-demo.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

SemedInstitucional/Views/Shared/_NoticiasBanner.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" height="300" src="~/SBAdmin/img/imei.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" height="300" src="~/SBAdmin/img/undraw_posting_photo.svg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" height="300" src="~/SBAdmin/img/undraw_posting_photo.svg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

SemedInstitucional/Views/Shared/_Sidebar.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-newspaper"></i>
            <span>NOTÍCIAS INTERNAS</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Home","Institucional")">
            <i class="fas fa-w fa-home"></i>
            <span>INSTITUCIONAL</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("SetoresInternos", "Setores")">
            <i class="fas fa-fw fa-object-group"></i>
            <span>SETORES</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Home", "CentroFormacao")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>CENTRO DE FORMAÇÃO</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Grupos")">
            <i class="fas fa-fw fa-users"></i>
            <span>GRUPOS</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("RedesEnsino", "Escolas")">
            <i class="fas fa-fw fa-book"></i>
            <span>ESCOLA DA REDE</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Configuracao")">
            <i class="fas fa-fw fa-cogs"></i>
            <span>CONFIGURAÇÃO</span>
        </a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
</ul>