SemedInstitucional/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SemedInstitucional.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SemedInstitucional/Controllers/InstitucionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SemedInstitucional.Controllers
{
    public class InstitucionalController : Controller
    {
        public ViewResult Home()
        {
            return View();
        }

        protected override void HandleUnknownAction(string actionName)
        {
            this.View(actionName).ExecuteResult(this.ControllerContext);
        }

    }
}

SemedInstitucional/Views/Institucional/HistoriaSemed.cshtml
@{
    ViewBag.Title = "HistoriaSemed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>HistoriaSemed</h2>

SemedInstitucional/Views/Institucional/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>INSTITUCIONAL</p>

<h5 style="background-color: lightgray; padding: 5px; font-weight: bold; font-size: 15px;">A SEMED</h5>
<ul>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("HistoriaSemed", "Institucional")">História Semed</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("PlanoGeral", "Institucional")">Plano Geral</a></li>
</ul>
<hr />
<h5 style="background-color: lightgray; padding: 5px; font-weight: bold; font-size: 15px;">POLÍTICA EDUCAR MAIS</h5>
<ul>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Diretrizes da Política Educar Mais</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Organograma Educar Mais</a></li>
</ul>
<hr />
<h5 style="background-color: lightgray; padding: 5px; font-weight: bold; font-size: 15px;">ORGANOGRAMAS</h5>
<ul>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Organograma Estrutural</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Organograma SAE</a></li>
</ul>
<hr />
<h5 style="background-color: lightgray; padding: 5px; font-weight: bold; font-size: 15px;">HIERARQUIAS</h5>
<ul>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Hierarquia Geral</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Hierarquia Setorial</a></li>
</ul>
<hr />
<h5 style="background-color: lightgray; padding: 5px; font-weight: bold; font-size: 15px;">PARCERIAS</h5>
<ul>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Alumar</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">CIEE</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">CMDCA</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">CORPO DE BOMBEIRO</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">FIEMA</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Fundação Lemann</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Instituto Federal do Maranhão - IFMA</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">SESC</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">SENAC</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">UNICEF</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Universidade Estadual do Maranhão - UEMA</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Universidade Federal do Maranhão - UFMA</a></li>
    <li class="font-weight-bold text-info" style="margin-bottom: 5px;"><a href="@Url.Action("", "")">Vale</a></li>
</ul>
<hr />